upstream ai_logo_backend {
    server 203.57.40.187:10160;
    #server 38.147.83.13:23460;
    #server 195.26.233.78:52715;
    #server ;
}

#upstream logo_maker_backend {
	#server 38.147.83.13:23460;
#}

upstream ai_image_vectorization_server {
    server unix:/run/ai-image-vectorization/gunicorn-ai-vectorization.sock fail_timeout=0;
}

server {
    listen 443 ssl;
    listen 8020 ssl;
    server_name logo-maker.online;
    ssl_certificate /etc/letsencrypt/live/logo-maker.online/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/logo-maker.online/privkey.pem;
    
    client_max_body_size 75M;
    # client_body_timeout 300s;
    # client_header_timeout 300s;

	
    # Add a root directory (you can create an empty directory if needed)
    root /var/www/html;
  

    location /m1/ {
       proxy_pass http://203.57.40.187:10160;
       proxy_connect_timeout 120s;
       proxy_send_timeout 120s;
       proxy_read_timeout 120s;
       send_timeout 120s;
       proxy_buffering off;
       proxy_max_temp_file_size 0;
     }


     location /m2/ {
       proxy_pass http://38.147.83.13:23460;
       proxy_connect_timeout 120s;
       proxy_send_timeout 120s;
       proxy_read_timeout 120s;
       send_timeout 120s;
       proxy_buffering off;
       proxy_max_temp_file_size 0;
     }

    #location /m3/ {
    #  proxy_pass http://;
    #}

    location /sdapi/v1/txt2logo {
        proxy_pass http://ai_logo_backend;
        
        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
        proxy_buffering off;
	proxy_max_temp_file_size 0;
    }
    
    location /sdapi/v1/temp2logo {
        proxy_pass http://ai_logo_backend;

	proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
        proxy_buffering off;
	proxy_max_temp_file_size 0;
    }

    location /ai/api/v2/logo-maker/txt2logo {
    	proxy_pass http://ai_logo_backend;
	
	proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
    }

    location /ai/api/v1/logo-maker/smart-edit {
        proxy_pass http://ai_logo_backend;

        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
    }

    location /ai/api/v2/logo-maker/temp2logo {
        proxy_pass http://ai_logo_backend;

        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
    }

    location /ai/api/v1/logo-maker/fix-txt {
        proxy_pass http://ai_logo_backend;

        proxy_connect_timeout 120s;
        proxy_send_timeout 120s;
        proxy_read_timeout 120s;
        send_timeout 120s;
        proxy_buffering off;
        proxy_max_temp_file_size 0;
    }

### AI Image Vectorization API Endpoints ###
   location /api/v1/vectorization {
   	proxy_pass http://ai_image_vectorization_server;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_buffering off;
   }

   location /media/vectorization/ {
   	alias /tmp/.temp/ai-image-vectorization/;
   }
### End ###

   location /style/style_json {
	alias /home/ai_logo/style_json/;
	try_files style_json.json =404;
	autoindex on;  # Optional: lists files if directory is visited
    }

   location /style/ {
        alias /home/ai_logo/style_image/;
        try_files $uri $uri/ =404;
        autoindex on;
    }

}
